# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(245, 284)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loadingGifLabel = QtWidgets.QLabel(self.verticalWidget_2)
        self.loadingGifLabel.setObjectName("loadingGifLabel")
        self.verticalLayout_2.addWidget(self.loadingGifLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.loadingBar = QtWidgets.QProgressBar(self.verticalWidget_2)
        self.loadingBar.setMaximum(50)
        self.loadingBar.setProperty("value", 25)
        self.loadingBar.setTextVisible(False)
        self.loadingBar.setOrientation(QtCore.Qt.Horizontal)
        self.loadingBar.setInvertedAppearance(False)
        self.loadingBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.loadingBar.setObjectName("loadingBar")
        self.verticalLayout_2.addWidget(self.loadingBar)
        self.loadingStatusLabel = QtWidgets.QLabel(self.verticalWidget_2)
        self.loadingStatusLabel.setObjectName("loadingStatusLabel")
        self.verticalLayout_2.addWidget(self.loadingStatusLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.verticalWidget_2, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadingGifLabel.setText(_translate("MainWindow", "image"))
        self.loadingStatusLabel.setText(_translate("MainWindow", "loading status"))
